// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:cd068ceb-9866-4df4-8b1a-46e8bca5575c",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_UanHW7w5k",
    "aws_user_pools_web_client_id": "5gjkom2c4itpd3bog4vjljo3oj",
    "oauth": {},
    "aws_content_delivery_bucket": "weadmit-ui-20191025005449-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-2",
    "aws_content_delivery_url": "http://weadmit-ui-20191025005449-hostingbucket-dev.s3-website.us-east-2.amazonaws.com"
};


export default awsmobile;
